#!/usr/bin/env python3
"""Generate magazine data, PDF cover images, and Google Drive link mappings."""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEBSITE_DIR = Path("/home/ved/Documents/sristi_pdf/all_pdf/website")
COVERS_DIR = ROOT / "frontend/public/assets/magazine_covers"
DRIVE_MAPPING = ROOT / "scripts/drive_pdf_mapping.json"
MAGAZINES_OUT = ROOT / "frontend/src/data/magazinesData.js"
DRIVE_LINKS_OUT = ROOT / "frontend/src/utils/googleDrivePdfLinks.js"
DRIVE_FOLDER = "https://drive.google.com/drive/folders/1DUOOxBuyYkrQI8owQe8RurP-jxTTpO7C?usp=sharing"

FOLDER_CATEGORY = {
    "Honey Bee (English)": "Honeybee",
    "Loksarvani (Gujarati)": "Loksarvani",
    "Suzbuz (Hindi)": "Suzbuz",
}

FOLDER_PREFIX = {
    "Honey Bee (English)": "Honey Bee Magazine",
    "Loksarvani (Gujarati)": "Loksarvani Magazine",
    "Suzbuz (Hindi)": "Suzbuz Magazine",
}

EXCERPTS = {
    "Honeybee": (
        "Explore stories of grassroots innovators, traditional knowledge, "
        "and creative persistence from the Honey Bee Network."
    ),
    "Loksarvani": (
        "Discover local wisdom, traditional agricultural practices, "
        "and ingenious solutions from across Gujarat."
    ),
    "Suzbuz": (
        "हिंदी में जमीनी नवप्रवर्तकों, पारंपरिक ज्ञान और रचनात्मक "
        "दृढ़ता की कहानियाँ — सुज़बुज़ पत्रिका।"
    ),
}


def slugify(name: str) -> str:
    s = name.replace(".pdf", "")
    s = re.sub(r"[^\w\s\-().&]", "", s, flags=re.UNICODE)
    s = re.sub(r"\s+", "_", s.strip())
    s = s.replace("(", "_").replace(")", "_")
    s = re.sub(r"_+", "_", s)
    return f"web_{s}-01"


def extract_year(filename: str) -> int:
    matches = re.findall(r"(19|20)\d{2}", filename)
    return int(matches[-1]) if matches else 2000


def extract_sort_key(filename: str, folder: str) -> tuple:
    year = extract_year(filename)
    nums = re.findall(r"\d+", filename.replace(".pdf", ""))
    issue = int(nums[0]) if nums else 0
    return (-year, -issue, filename.lower())


def generate_cover(pdf_path: Path, cover_path: Path) -> bool:
    if cover_path.exists() and cover_path.stat().st_mtime >= pdf_path.stat().st_mtime:
        return False
    cover_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_prefix = cover_path.with_suffix("")
    subprocess.run(
        [
            "pdftoppm",
            "-jpeg",
            "-f",
            "1",
            "-l",
            "1",
            "-scale-to",
            "600",
            str(pdf_path),
            str(tmp_prefix),
        ],
        check=True,
        capture_output=True,
    )
    generated = Path(f"{tmp_prefix}-1.jpg")
    if not generated.exists():
        generated = Path(f"{tmp_prefix}-01.jpg")
    if generated.exists():
        generated.rename(cover_path)
        return True
    return False


def js_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def build_magazines(drive_map: dict) -> list[dict]:
    magazines = []
    mag_id = 1

    for folder_name, category in FOLDER_CATEGORY.items():
        folder_path = WEBSITE_DIR / folder_name
        if not folder_path.exists():
            print(f"Warning: missing folder {folder_path}", file=sys.stderr)
            continue

        pdfs = sorted(folder_path.glob("*.pdf"), key=lambda p: extract_sort_key(p.name, folder_name))

        for pdf in pdfs:
            slug = slugify(pdf.name)
            cover_file = f"{slug}.jpg"
            cover_path = COVERS_DIR / cover_file
            rel_pdf = f"/sristi_pdf/all_pdf/website/{folder_name}/{pdf.name}"

            try:
                if generate_cover(pdf, cover_path):
                    print(f"  cover: {cover_file}")
            except subprocess.CalledProcessError as e:
                print(f"  cover FAILED: {pdf.name}: {e.stderr.decode()[:120]}", file=sys.stderr)

            year = extract_year(pdf.name)
            magazines.append(
                {
                    "id": mag_id,
                    "title": f"{FOLDER_PREFIX[folder_name]} - {pdf.stem}",
                    "category": category,
                    "date": f"January 1, {year}",
                    "datetime": f"{year}-01-01",
                    "coverImage": f"/assets/magazine_covers/{cover_file}",
                    "pdfLink": rel_pdf,
                    "excerpt": EXCERPTS[category],
                }
            )
            mag_id += 1

    return magazines


def write_magazines_js(magazines: list[dict]) -> None:
    lines = ["// Auto-generated by scripts/generate_magazines.py — do not edit manually\n", "export const MAGAZINES = [\n"]
    for m in magazines:
        lines.append("  {\n")
        lines.append(f"    id: {m['id']},\n")
        lines.append(f"    title: {js_str(m['title'])},\n")
        lines.append(f"    category: {js_str(m['category'])},\n")
        lines.append(f"    date: {js_str(m['date'])},\n")
        lines.append(f"    datetime: {js_str(m['datetime'])},\n")
        lines.append(f"    coverImage: {js_str(m['coverImage'])},\n")
        lines.append(f"    pdfLink: {js_str(m['pdfLink'])},\n")
        lines.append(f"    excerpt: {js_str(m['excerpt'])},\n")
        lines.append("  },\n")
    lines.append("];\n")
    MAGAZINES_OUT.parent.mkdir(parents=True, exist_ok=True)
    MAGAZINES_OUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {len(magazines)} magazines -> {MAGAZINES_OUT}")


def write_drive_links_js(drive_map: dict) -> None:
    lines = [
        f"// Auto-generated from Google Drive folder: {DRIVE_FOLDER}\n\n",
        "const PDF_DRIVE_LINKS = {\n",
    ]
    for filename in sorted(drive_map.keys(), key=str.lower):
        lines.append(f"  {js_str(filename)}: {js_str(drive_map[filename])},\n")
    lines.append("};\n\n")
    lines.append(f"export const GOOGLE_DRIVE_FOLDER = {js_str(DRIVE_FOLDER)};\n\n")
    lines.append(
        "/**\n"
        " * Resolve a local PDF path or filename to its Google Drive view link.\n"
        " * External URLs (http/https) are returned unchanged.\n"
        " */\n"
        "export function getGoogleDriveLink(pdfLink) {\n"
        "  if (!pdfLink) return null;\n"
        "  if (/^https?:\\/\\//i.test(pdfLink)) return pdfLink;\n"
        "  const filename = pdfLink.split('/').pop();\n"
        "  return PDF_DRIVE_LINKS[filename] ?? null;\n"
        "}\n"
    )
    DRIVE_LINKS_OUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {len(drive_map)} drive links -> {DRIVE_LINKS_OUT}")


def main() -> None:
    if not DRIVE_MAPPING.exists():
        print(f"Missing {DRIVE_MAPPING}. Run drive fetch first.", file=sys.stderr)
        sys.exit(1)

    drive_map = json.loads(DRIVE_MAPPING.read_text(encoding="utf-8"))
    COVERS_DIR.mkdir(parents=True, exist_ok=True)

    print("Generating PDF cover images...")
    magazines = build_magazines(drive_map)
    write_magazines_js(magazines)
    write_drive_links_js(drive_map)
    print("Done.")


if __name__ == "__main__":
    main()
